# Generated by Django 5.1.15 on 2026-06-24 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('grammar', 'Grammar'), ('dialog', 'Dialog'), ('vocabulary', 'Vocabulary'), ('listening', 'Listening'), ('writing', 'Writing'), ('reading', 'Reading'), ('freeform', 'Freeform')], default='freeform', max_length=20)),
                ('body_markdown', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_notes_mynote',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='my_notes_my_user_id_44af19_idx'), models.Index(fields=['user', 'kind'], name='my_notes_my_user_id_80337b_idx'), models.Index(fields=['is_public', '-updated_at'], name='my_notes_my_is_publ_2ea39e_idx')],
            },
        ),
    ]
