# Generated by Django 5.1.15 on 2026-04-05 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='image_queries/')),
                ('question', models.TextField(blank=True, default='')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('ai_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_queries', to='assistant.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_image_queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
