# Generated by Django 5.1.15 on 2026-05-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_imagequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
