# Generated by Django 5.1.15 on 2026-04-05 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'News'), ('word', 'Word of the Day'), ('grammar', 'Grammar Tip'), ('trivia', 'Trivia')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('content_json', models.JSONField(default=dict)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discover_cards',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDiscoverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('interacted', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='discover.discovercard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discover_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discover_user_history',
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='unique_user_card_history')],
            },
        ),
    ]
