# Generated by Django 5.1.15 on 2026-04-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovercard',
            name='level',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='discovercard',
            name='topic',
            field=models.CharField(blank=True, choices=[('politics', 'Politics'), ('sports', 'Sports'), ('culture', 'Culture'), ('economy', 'Economy'), ('science', 'Science'), ('tech', 'Technology'), ('society', 'Society'), ('environ', 'Environment'), ('world', 'World'), ('misc', 'Miscellaneous')], default='', max_length=12),
        ),
    ]
