# Generated by Django 5.1.15 on 2026-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_discovercard_level_discovercard_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovercard',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
    ]
