# Generated by Django 5.1.15 on 2026-06-27 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_discovercard_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('fact_fr', models.TextField()),
                ('fact_en', models.TextField(blank=True, default='')),
                ('level', models.CharField(blank=True, default='', max_length=2)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discover_trivia_templates',
                'ordering': ['language', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'language'), name='unique_trivia_slug_per_lang')],
            },
        ),
        migrations.CreateModel(
            name='UserTriviaSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='discover.triviatemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discover_user_trivia_seen',
                'constraints': [models.UniqueConstraint(fields=('user', 'template'), name='unique_user_trivia_seen')],
            },
        ),
    ]
