services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  django:
    build: ./backend
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    volumes:
      - ./backend:/app
      - static_files:/app/staticfiles
      - media_files:/app/media
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    volumes:
      - ./backend:/app

  celery-beat:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    volumes:
      - ./backend:/app

  nginx:
    ports:
      - "80:80"
