# Generated by Django 5.1.15 on 2026-05-07 15:44

from django.db import migrations, models


def backfill_existing_users(apps, schema_editor):
    """Existing users (signed up before mode existed) shouldn't be blocked by
    the onboarding modal. Default them to ``general``. Newly-created users
    keep ``mode=None`` so they DO see the picker on first login."""
    User = apps.get_model("users", "User")
    User.objects.filter(mode__isnull=True).update(mode="general")


def noop_reverse(apps, schema_editor):
    # Reverse: nothing to undo, the columns get dropped by the schema half
    # of this migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(blank=True, choices=[('general', 'General Learner'), ('exam', 'Exam Prep (TCF / TEF)'), ('agentic', 'Agentic, assistant first')], help_text="Audience persona. Null means the user hasn't been onboarded.", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proficiency_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency'), ('unsure', 'Pas sûr / placement test')], help_text='Self-reported CEFR level. Distinct from target_level.', max_length=8, null=True),
        ),
        migrations.RunPython(backfill_existing_users, noop_reverse),
    ]
