# Generated by Django 5.1.15 on 2026-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_mode_user_proficiency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'Français')], help_text='Language for the app chrome (nav, settings, buttons). Distinct from native_language (the language the user thinks in) and from the language being learned (always French). Null means: detect from the browser on first load.', max_length=4, null=True),
        ),
    ]
