# Generated by Django 5.1.15 on 2026-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ui_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', help_text='The language the user is learning. Distinct from native_language (what they speak natively) and ui_language (the app chrome).', max_length=8),
        ),
    ]
