# Generated by Django 5.1.15 on 2026-04-30 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0002_imagequery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('emoji', models.CharField(default='✨', max_length=8)),
                ('tint', models.CharField(default='from-primary-500 to-purple-600', help_text='Tailwind gradient pair for the avatar / top band.', max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('best_for', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('suggested_questions', models.JSONField(blank=True, default=list)),
                ('system_prompt', models.TextField(help_text='System prompt sent to the LLM for every turn of this agent.')),
                ('mode', models.CharField(choices=[('conversation', 'Conversation'), ('grammar_correction', 'Grammar Correction'), ('grammar_explanation', 'Grammar Explanation')], default='conversation', max_length=24)),
                ('output_shape', models.CharField(choices=[('free_text', 'Free text'), ('structured', 'Structured')], default='free_text', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents_agent',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='assistant.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'agent', '-started_at'], name='agents_run_user_id_706f0a_idx')],
            },
        ),
    ]
