# Generated by Django 5.1.15 on 2026-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_append_blocks_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='system_prompt_en',
            field=models.TextField(blank=True, default='', help_text='System prompt for EN learners. Falls back to system_prompt if empty.'),
        ),
    ]
