# Generated by Django 5.1.15 on 2026-04-05 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('mistake_type', models.CharField(choices=[('gender', 'Gender'), ('conjugation', 'Conjugation'), ('preposition', 'Preposition'), ('spelling', 'Spelling'), ('other', 'Other')], default='other', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_mistakes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SRSCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('last_quality', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='content.vocabulary')),
            ],
            options={
                'db_table': 'progress_srs_cards',
                'ordering': ['next_review_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'vocabulary'), name='unique_srs_card_per_user_vocab')],
            },
        ),
    ]
