# Generated by Django 5.1.15 on 2026-04-05 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vocab', 'Vocabulary'), ('grammar', 'Grammar'), ('text', 'Reading Text')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField()),
                ('difficulty', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'content_lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('difficulty_level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'content_topics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('explanation', models.TextField()),
                ('formula', models.CharField(blank=True, default='', max_length=500)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_rules', to='content.lesson')),
            ],
            options={
                'db_table': 'content_grammar_rules',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('translate', 'Translation'), ('match', 'Matching'), ('listen', 'Listening'), ('cloze', 'Cloze'), ('conjugation', 'Conjugation')], max_length=15)),
                ('prompt', models.TextField()),
                ('correct_answer', models.TextField()),
                ('wrong_answers', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('difficulty', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.lesson')),
            ],
            options={
                'db_table': 'content_questions',
            },
        ),
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('vocabulary_highlights', models.JSONField(blank=True, default=list)),
                ('comprehension_questions', models.JSONField(blank=True, default=list)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_texts', to='content.lesson')),
            ],
            options={
                'db_table': 'content_reading_texts',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.topic'),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.CharField(max_length=300)),
                ('english', models.CharField(max_length=300)),
                ('pronunciation', models.CharField(blank=True, default='', max_length=200)),
                ('example_sentence', models.TextField(blank=True, default='')),
                ('gender', models.CharField(choices=[('m', 'Masculine'), ('f', 'Feminine'), ('n', 'Neutral'), ('a', 'Not Applicable')], default='a', max_length=1)),
                ('part_of_speech', models.CharField(blank=True, default='', max_length=50)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='content.lesson')),
            ],
            options={
                'verbose_name_plural': 'vocabulary',
                'db_table': 'content_vocabulary',
            },
        ),
    ]
