# Generated by Django 5.1.15 on 2026-04-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=500)),
                ('youtube_id', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript_fr', models.TextField(blank=True, default='')),
                ('transcript_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='content.lesson')),
            ],
            options={
                'db_table': 'content_video_lessons',
            },
        ),
        migrations.CreateModel(
            name='VideoExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_fr', models.CharField(max_length=500)),
                ('expression_en', models.CharField(max_length=500)),
                ('context_sentence', models.TextField(blank=True, default='')),
                ('timestamp_seconds', models.PositiveIntegerField(default=0)),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='content.videolesson')),
            ],
            options={
                'db_table': 'content_video_expressions',
            },
        ),
        migrations.CreateModel(
            name='VideoVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.CharField(max_length=300)),
                ('english', models.CharField(max_length=300)),
                ('pronunciation', models.CharField(blank=True, default='', max_length=200)),
                ('example_sentence', models.TextField(blank=True, default='')),
                ('timestamp_seconds', models.PositiveIntegerField(default=0)),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='content.videolesson')),
            ],
            options={
                'verbose_name_plural': 'video vocabulary',
                'db_table': 'content_video_vocabulary',
            },
        ),
    ]
