# Generated by Django 5.1.15 on 2026-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_video_lesson_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrule',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='readingtext',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='topic',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
    ]
