# Generated by Django 5.1.15 on 2026-05-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='en', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notes_note',
                'ordering': ['-note_number'],
                'indexes': [models.Index(fields=['language', '-note_number'], name='notes_note_languag_3e862d_idx')],
                'constraints': [models.UniqueConstraint(fields=('language', 'note_number'), name='notes_unique_lang_number')],
            },
        ),
        migrations.CreateModel(
            name='NoteWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True, default='')),
                ('example', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='notes.note')),
            ],
            options={
                'db_table': 'notes_word',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['note', 'order'], name='notes_word_note_id_2c3505_idx')],
            },
        ),
    ]
