# Generated by Django 5.1.15 on 2026-04-26 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'grammar categories',
                'db_table': 'grammar_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrammarDrillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fill_blank', 'Fill in the blank'), ('mcq', 'Multiple choice'), ('transform', 'Transform the sentence'), ('error_detect', 'Spot the error'), ('reorder', 'Reorder the words')], default='fill_blank', max_length=15)),
                ('prompt', models.TextField()),
                ('correct_answer', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'grammar_drill_items',
            },
        ),
        migrations.CreateModel(
            name='GrammarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('drill', 'Drill'), ('diagnostic', 'Diagnostic')], default='drill', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('mastery_before', models.FloatField(blank=True, null=True)),
                ('mastery_after', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grammar_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('drill_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='grammar.grammardrillitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grammar.grammarsession')),
            ],
            options={
                'db_table': 'grammar_answers',
            },
        ),
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A2', max_length=2)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('explanation', models.TextField()),
                ('formula', models.CharField(blank=True, default='', max_length=400)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('common_mistakes', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='grammar.grammarcategory')),
            ],
            options={
                'db_table': 'grammar_topics',
                'ordering': ['category__order', 'order', 'cefr_level'],
            },
        ),
        migrations.AddField(
            model_name='grammarsession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='grammar.grammartopic'),
        ),
        migrations.AddField(
            model_name='grammardrillitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='grammar.grammartopic'),
        ),
        migrations.CreateModel(
            name='GrammarMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('mastery_score', models.FloatField(default=0)),
                ('last_drilled_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('interval_days', models.FloatField(default=1.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_mastery', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='grammar.grammartopic')),
            ],
            options={
                'verbose_name_plural': 'grammar mastery records',
                'db_table': 'grammar_mastery',
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='unique_grammar_mastery')],
            },
        ),
    ]
