# Generated by Django 5.1.15 on 2026-05-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcategory',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='grammardrillitem',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
    ]
