# Generated by Django 5.1.15 on 2026-04-05 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('language', models.CharField(default='fr', max_length=10)),
                ('provider', models.CharField(choices=[('gtts', 'Google TTS (gTTS)')], default='gtts', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_audio_clips',
                'constraints': [models.UniqueConstraint(fields=('text_content', 'language'), name='unique_text_language')],
            },
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_text', models.TextField()),
                ('audio_file', models.FileField(upload_to='pronunciation/')),
                ('transcription', models.TextField(blank=True, default='')),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_attempts', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronunciation_attempts', to='content.vocabulary')),
            ],
            options={
                'db_table': 'media_pronunciation_attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
