# Generated by Django 5.1.15 on 2026-04-11 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('CO', 'Compréhension orale'), ('CE', 'Compréhension écrite'), ('EE', 'Expression écrite'), ('EO', 'Expression orale')], max_length=2)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], max_length=2)),
                ('title', models.CharField(max_length=300)),
                ('instructions_fr', models.TextField(blank=True, default='')),
                ('instructions_en', models.TextField(blank=True, default='')),
                ('content', models.JSONField(default=dict)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam_prep_exercises',
                'ordering': ['order', 'cefr_level'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('CO', 'Compréhension orale'), ('CE', 'Compréhension écrite'), ('EE', 'Expression écrite'), ('EO', 'Expression orale')], max_length=2)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], max_length=2)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('mock', 'Mock Exam')], default='practice', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_prep_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField(default=0)),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=1)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exam_prep.examexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exam_prep.examsession')),
            ],
            options={
                'db_table': 'exam_prep_responses',
            },
        ),
        migrations.CreateModel(
            name='ExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('CO', 'Compréhension orale'), ('CE', 'Compréhension écrite'), ('EE', 'Expression écrite'), ('EO', 'Expression orale')], max_length=2)),
                ('best_score_pct', models.FloatField(default=0)),
                ('exercises_completed', models.PositiveIntegerField(default=0)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('estimated_cefr_level', models.CharField(blank=True, default='', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_prep_progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'section'), name='unique_exam_progress_per_section')],
            },
        ),
    ]
