# Generated by Django 5.1.15 on 2026-06-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_prep', '0002_examexercise_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresponse',
            name='grading_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresponse',
            name='grading_status',
            field=models.CharField(choices=[('not_required', 'Not required (auto-graded)'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='examresponse',
            name='grading_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
