# Generated by Django 5.1.15 on 2026-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lookup', 'Lookup'), ('conjugation', 'Conjugation')], max_length=12)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('kind', 'key')},
            },
        ),
    ]
