# Generated by Django 5.1.15 on 2026-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionarycache',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dictionarycache',
            name='source',
            field=models.CharField(choices=[('seed', 'Seed'), ('runtime', 'Runtime')], db_index=True, default='runtime', max_length=16),
        ),
        migrations.AddField(
            model_name='dictionarycache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
