# Generated by Django 5.1.15 on 2026-05-18 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('goal', 'Goal'), ('preference', 'Preference'), ('background', 'Background'), ('weakness', 'Weakness'), ('other', 'Other')], default='other', max_length=16)),
                ('source', models.CharField(choices=[('user', 'User-authored'), ('assistant_detected', 'Detected by assistant')], default='user', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memory_notes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active', '-updated_at'], name='memory_note_user_id_9d2179_idx')],
            },
        ),
    ]
