# Generated by Django 5.1.15 on 2026-05-18 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_memoryextractionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memorynote',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], db_index=True, default='fr', max_length=8),
        ),
        migrations.AddIndex(
            model_name='memorynote',
            index=models.Index(fields=['user', 'language', 'is_active'], name='memory_note_user_id_cb3dc0_idx'),
        ),
    ]
